### start-server UDP
POST http://localhost:3000/start-server
Content-Type: application/json

{
    "serverType": "UDP"
}

### send-client-msg UDP
POST http://localhost:3000/start-client
Content-Type: application/json

{
    "clientType": "UDP",
    "msg": "Hola mundo con UDP",
    "msgType": "debug"
}

### start-server TCP
POST http://localhost:3000/start-server
Content-Type: application/json

{
    "serverType": "TCP"
    
}

### send-client-msg TCP
POST http://localhost:3000/start-client
Content-Type: application/json

{
    "clientType": "TCP",
    "msg": "Hola uru con TCP",
    "msgType": "debug"
}

###kill-server
POST http://localhost:3000/stop-server