### start-server
POST http://localhost:3000/start-server
Content-Type: application/json

{
    "serverType": "UDP"
}

### send-client-msg
POST http://localhost:3000/start-client
Content-Type: application/json

{
    "clientType": "UDP"
}

###kill-server
POST http://localhost:3000/stop-server